
# The x86_64-unknown-none target is exactly what we want here. It uses the kernel code model, and uses softfloat (no
# SSE, etc).
#
# See: https://doc.rust-lang.org/nightly/rustc/platform-support/x86_64-unknown-none.html
[build]
target = "x86_64-unknown-none"

[target.x86_64-unknown-none]
rustflags = [
    "-Clink-arg=-Tlinker.lds",
    "-Crelocation-model=static",
    "-Clink-arg=-no-pie",
    "-Cpanic=abort",
    "-Ctarget-cpu=x86-64-v3",
]
